{
  "hash": "b4fde3084a1eb10f24bc63c575f3f31b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Customer Shopping Trends Analysis\"\nauthor: Tongtong Gu\nlisting:\n  contents: posts\n  sort: \"date desc\"\n  type: default\n  categories: true\n  sort-ui: false\n  filter-ui: false\npage-layout: full\ntitle-block-banner: true\nformat:\n  html:\n    toc: true\n    number-sections: true\n---\n\n\n\n### *Exploratory Data Analysis*\n\nDataset Source\n\nThe dataset used for this analysis is the Customer Shopping (Latest Trends) Dataset, available on Kaggle. It provides valuable insights into customer shopping habits, including demographic details, purchase behaviors, and product trends.\n\nSource: Customer Shopping (Latest Trends) Dataset(https://www.kaggle.com/datasets/bhadramohit/customer-shopping-latest-trends-dataset)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(caret)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lattice\n```\n\n\n:::\n\n```{.r .cell-code}\ndataset <- read.csv(\"shopping_trends.csv\")\n\nstr(dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t3900 obs. of  19 variables:\n $ Customer.ID             : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Age                     : int  55 19 50 21 45 46 63 27 26 57 ...\n $ Gender                  : chr  \"Male\" \"Male\" \"Male\" \"Male\" ...\n $ Item.Purchased          : chr  \"Blouse\" \"Sweater\" \"Jeans\" \"Sandals\" ...\n $ Category                : chr  \"Clothing\" \"Clothing\" \"Clothing\" \"Footwear\" ...\n $ Purchase.Amount..USD.   : int  53 64 73 90 49 20 85 34 97 31 ...\n $ Location                : chr  \"Kentucky\" \"Maine\" \"Massachusetts\" \"Rhode Island\" ...\n $ Size                    : chr  \"L\" \"L\" \"S\" \"M\" ...\n $ Color                   : chr  \"Gray\" \"Maroon\" \"Maroon\" \"Maroon\" ...\n $ Season                  : chr  \"Winter\" \"Winter\" \"Spring\" \"Spring\" ...\n $ Review.Rating           : num  3.1 3.1 3.1 3.5 2.7 2.9 3.2 3.2 2.6 4.8 ...\n $ Subscription.Status     : chr  \"Yes\" \"Yes\" \"Yes\" \"Yes\" ...\n $ Payment.Method          : chr  \"Credit Card\" \"Bank Transfer\" \"Cash\" \"PayPal\" ...\n $ Shipping.Type           : chr  \"Express\" \"Express\" \"Free Shipping\" \"Next Day Air\" ...\n $ Discount.Applied        : chr  \"Yes\" \"Yes\" \"Yes\" \"Yes\" ...\n $ Promo.Code.Used         : chr  \"Yes\" \"Yes\" \"Yes\" \"Yes\" ...\n $ Previous.Purchases      : int  14 2 23 49 31 14 49 19 8 4 ...\n $ Preferred.Payment.Method: chr  \"Venmo\" \"Cash\" \"Credit Card\" \"PayPal\" ...\n $ Frequency.of.Purchases  : chr  \"Fortnightly\" \"Fortnightly\" \"Weekly\" \"Weekly\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Customer.ID          Age           Gender          Item.Purchased    \n Min.   :   1.0   Min.   :18.00   Length:3900        Length:3900       \n 1st Qu.: 975.8   1st Qu.:31.00   Class :character   Class :character  \n Median :1950.5   Median :44.00   Mode  :character   Mode  :character  \n Mean   :1950.5   Mean   :44.07                                        \n 3rd Qu.:2925.2   3rd Qu.:57.00                                        \n Max.   :3900.0   Max.   :70.00                                        \n   Category         Purchase.Amount..USD.   Location             Size          \n Length:3900        Min.   : 20.00        Length:3900        Length:3900       \n Class :character   1st Qu.: 39.00        Class :character   Class :character  \n Mode  :character   Median : 60.00        Mode  :character   Mode  :character  \n                    Mean   : 59.76                                             \n                    3rd Qu.: 81.00                                             \n                    Max.   :100.00                                             \n    Color              Season          Review.Rating  Subscription.Status\n Length:3900        Length:3900        Min.   :2.50   Length:3900        \n Class :character   Class :character   1st Qu.:3.10   Class :character   \n Mode  :character   Mode  :character   Median :3.70   Mode  :character   \n                                       Mean   :3.75                      \n                                       3rd Qu.:4.40                      \n                                       Max.   :5.00                      \n Payment.Method     Shipping.Type      Discount.Applied   Promo.Code.Used   \n Length:3900        Length:3900        Length:3900        Length:3900       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n Previous.Purchases Preferred.Payment.Method Frequency.of.Purchases\n Min.   : 1.00      Length:3900              Length:3900           \n 1st Qu.:13.00      Class :character         Class :character      \n Median :25.00      Mode  :character         Mode  :character      \n Mean   :25.35                                                     \n 3rd Qu.:38.00                                                     \n Max.   :50.00                                                     \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Customer.ID Age Gender Item.Purchased Category Purchase.Amount..USD.\n1           1  55   Male         Blouse Clothing                    53\n2           2  19   Male        Sweater Clothing                    64\n3           3  50   Male          Jeans Clothing                    73\n4           4  21   Male        Sandals Footwear                    90\n5           5  45   Male         Blouse Clothing                    49\n6           6  46   Male       Sneakers Footwear                    20\n       Location Size     Color Season Review.Rating Subscription.Status\n1      Kentucky    L      Gray Winter           3.1                 Yes\n2         Maine    L    Maroon Winter           3.1                 Yes\n3 Massachusetts    S    Maroon Spring           3.1                 Yes\n4  Rhode Island    M    Maroon Spring           3.5                 Yes\n5        Oregon    M Turquoise Spring           2.7                 Yes\n6       Wyoming    M     White Summer           2.9                 Yes\n  Payment.Method Shipping.Type Discount.Applied Promo.Code.Used\n1    Credit Card       Express              Yes             Yes\n2  Bank Transfer       Express              Yes             Yes\n3           Cash Free Shipping              Yes             Yes\n4         PayPal  Next Day Air              Yes             Yes\n5           Cash Free Shipping              Yes             Yes\n6          Venmo      Standard              Yes             Yes\n  Previous.Purchases Preferred.Payment.Method Frequency.of.Purchases\n1                 14                    Venmo            Fortnightly\n2                  2                     Cash            Fortnightly\n3                 23              Credit Card                 Weekly\n4                 49                   PayPal                 Weekly\n5                 31                   PayPal               Annually\n6                 14                    Venmo                 Weekly\n```\n\n\n:::\n:::\n\n\n\nThe bar plot below illustrates the distribution of product categories purchased by customers. Clothing dominates as the most popular category, followed by Accessories, Footwear, and Outerwear. This suggests that clothing is a primary focus area for customer demand. However, outerwear shows significantly lower engagement, highlighting an opportunity for targeted promotions or campaigns to boost sales in this category.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bar plot\nggplot(dataset, aes(x = Category)) +\n  geom_bar(fill = \"skyblue\") +\n  theme_minimal() +\n  labs(title = \"Distribution of Categories\", x = \"Category\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](Customer-Shopping-Trends-Analysis_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n### *Predictive Analysis*\n\nObjective: A linear regression model was constructed to predict the Purchase_Amount using Age and Review_Rating. These variables were chosen based on their potential influence on customer purchasing behavior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Predictive Analysis:Linear regression\ndataset <- dataset %>%\n  rename(Purchase_Amount = Purchase.Amount..USD.)  # Simplify column name\n\ndataset <- dataset %>%\n  filter(!is.na(Purchase_Amount) & Purchase_Amount > 0)\n\nset.seed(123)\ntraining_index <- createDataPartition(dataset$Purchase_Amount, p = 0.8, list = FALSE)\ntraining_set <- dataset[training_index, ]\ntest_set <- dataset[-training_index, ]\n\nmodel <- lm(Purchase_Amount ~ Age + Review.Rating, data = training_set)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Purchase_Amount ~ Age + Review.Rating, data = training_set)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-41.245 -21.310   0.016  20.770  41.883 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   57.78143    2.59555  22.262   <2e-16 ***\nAge           -0.02913    0.02774  -1.050    0.294    \nReview.Rating  0.87959    0.59398   1.481    0.139    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 23.69 on 3119 degrees of freedom\nMultiple R-squared:  0.001073,\tAdjusted R-squared:  0.0004325 \nF-statistic: 1.675 on 2 and 3119 DF,  p-value: 0.1874\n```\n\n\n:::\n\n```{.r .cell-code}\ntest_set$Predicted_Purchase <- predict(model, test_set)\n\nrmse <- sqrt(mean((test_set$Purchase_Amount - test_set$Predicted_Purchase)^2))\nprint(paste(\"RMSE:\", rmse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"RMSE: 23.6512501921126\"\n```\n\n\n:::\n:::\n\n\n\nThe regression analysis reveals the following:\n\nThe intercept estimate of 57.78 suggests that the baseline average purchase amount is approximately \\$57.78 when other variables are at their reference levels. Age has a small, non-significant negative coefficient (-0.029), implying minimal impact on spending behavior. Review_Rating has a positive but non-significant effect (coefficient = 0.88). This suggests that higher ratings may correlate with slightly higher purchases, but the relationship is weak. The model’s Adjusted R-squared value is 0.0004, indicating that only a negligible portion of the variance in purchase amounts is explained by Age and Review_Rating. Additionally, the residual standard error (RSE) of 23.69 and the RMSE of \\~23.65 highlight significant prediction errors, which are substantial relative to the purchase amount range (\\$20–\\$100).\n\n### *Visualization: Actual vs Predicted*\n\nThe scatter plot below compares the actual and predicted purchase amounts. The wide scatter around the ideal prediction line (red dashed) reflects poor alignment between predicted and actual values, reinforcing the model's low predictive power. This suggests that Age and Review_Rating are insufficient predictors of Purchase_Amount.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualization: Predicted vs Actual Spend\nggplot(test_set, aes(x = Purchase_Amount, y = Predicted_Purchase)) +\n  geom_point(color = \"blue\") +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", color = \"red\") +\n  theme_minimal() +\n  labs(title = \"Actual vs Predicted Purchase Amount\", x = \"Actual Amount\", y = \"Predicted Amount\")\n```\n\n::: {.cell-output-display}\n![](Customer-Shopping-Trends-Analysis_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n### *Conclusion*\n\nThis analysis highlights key trends in customer shopping behavior and identifies opportunities to enhance predictive accuracy. While the current model does not perform well, incorporating additional variables and exploring alternative modeling techniques could significantly improve the insights derived from this dataset.\n",
    "supporting": [
      "Customer-Shopping-Trends-Analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}