{
  "hash": "8429315ad936f83623327822fe918b06",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Life Expectancy Analysis: A Global Perspective\"\nauthor: Tongtong Gu\n\nlisting:\n  contents: posts\n  sort: \"date desc\"\n  type: default\n  categories: true\n  sort-ui: false\n  filter-ui: false\npage-layout: full\ntitle-block-banner: true\nformat:\n  html:\n    toc: true\n    number-sections: true\n---\n\n\n\n### *Introduction*\n\nThis analysis explores the Life Expectancy Averaged Dataset, highlighting global trends in life expectancy and the impact of socio-economic and health factors. The dataset contains life expectancy data across countries and regions, along with associated indicators like GDP, education levels, and infant mortality. This analysis leverages visualizations and predictive modeling to identify key drivers of life expectancy.\n\nDataset Source The dataset used in this analysis is available on Kaggle:https://www.kaggle.com/datasets/shreyasg23/life-expectancy-averaged-dataset\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\ndataset <- read.csv(\"life-expectancy-dataset.csv\")\n\nhead(dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Country                        Region   Year Infant_deaths\n1         Afghanistan                          Asia 2007.5      71.08125\n2             Albania                Rest of Europe 2007.5      15.25625\n3             Algeria                        Africa 2007.5      26.75625\n4              Angola                        Africa 2007.5      88.76875\n5 Antigua and Barbuda Central America and Caribbean 2007.5       9.47500\n6           Argentina                 South America 2007.5      13.85000\n  Under_five_deaths Adult_mortality Alcohol_consumption Hepatitis_B Measles\n1          98.61250       265.80497            0.016125     64.5625 24.3750\n2          17.14375        83.13297            4.696875     98.0000 95.9375\n3          31.19375       113.43928            0.400625     88.3125 93.2500\n4         144.16250       297.84406            4.935625     68.8125 64.0000\n5          11.51875       142.47881            7.755000     98.2500 75.4375\n6          15.50625       127.91266            7.959375     85.3125 84.6875\n       BMI   Polio Diphtheria Incidents_HIV GDP_per_capita Population_mln\n1 22.46250 55.3750    55.1250      0.022500       408.5625      27.450625\n2 25.85625 98.1250    98.0625      0.025625      3071.1250       2.969375\n3 24.86875 91.7500    91.8750      0.021875      3745.1250      34.820625\n4 22.51875 35.7500    55.5625      1.303750      2647.8125      21.623750\n5 25.85000 96.9375    98.3125      0.125000     14678.7500       0.085000\n6 26.85000 92.2500    92.3750      0.145625     12169.1250      39.913125\n  Thinness_ten_nineteen_years Thinness_five_nine_years Schooling Economy_status\n1                    16.58125                 15.58125   2.90000              1\n2                     1.61875                  1.70000   9.24375              1\n3                     6.09375                  5.97500   6.99375              1\n4                     6.19375                  6.66875   4.60625              1\n5                     3.42500                  3.37500   9.01875              1\n6                     1.07500                  0.95000   9.36875              1\n  Life_expectancy\n1        59.65625\n2        75.95000\n3        73.78750\n4        52.82500\n5        75.35000\n6        74.86250\n```\n\n\n:::\n:::\n\n\n\n\\###*Exploratory Data Analysis*\n\nThe histogram shows the global distribution of life expectancy. Most countries have a life expectancy between 60 and 80 years, with a small number of outliers on both ends. This reflects disparities between developed and developing nations, where factors like healthcare access and socio-economic status play a significant role.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Life expectancy histogram\nggplot(dataset, aes(x = Life_expectancy)) +\n  geom_histogram(binwidth = 2, fill = \"skyblue\", color = \"black\") +\n  theme_minimal() +\n  labs(\n    title = \"Distribution of Life Expectancy\",\n    x = \"Life Expectancy (years)\",\n    y = \"Frequency\"\n  )\n```\n\n::: {.cell-output-display}\n![](Life-Expectancy-Averaged_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\nhe boxplot highlights regional differences in life expectancy:\n\nAfrica has the lowest median life expectancy, likely due to higher disease prevalence, lower immunization rates, and economic challenges. Europe, North America, and Oceania exhibit the highest life expectancy, supported by robust healthcare systems and higher GDP. Asia and South America show moderate life expectancy with notable variation across countries.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Life expectancy by region (boxplot)\nggplot(dataset, aes(x = Region, y = Life_expectancy, fill = Region)) +\n  geom_boxplot() +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  labs(\n    title = \"Life Expectancy by Region\",\n    x = \"Region\",\n    y = \"Life Expectancy (years)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Life-Expectancy-Averaged_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\\###*Predictive Modeling*\n\nObjective\n\nDevelop a linear regression model to predict life expectancy based on key indicators:\n\nGDP_per_capita: Represents economic prosperity.\n\nSchooling: Average years of education, reflecting access to knowledge.\n\nInfant_deaths: A critical health indicator, inversely correlated with life expectancy.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ntraining_index <- sample(1:nrow(dataset), 0.8 * nrow(dataset))\ntraining_set <- dataset[training_index, ]\ntest_set <- dataset[-training_index, ]\n\nmodel <- lm(Life_expectancy ~ GDP_per_capita + Schooling + Infant_deaths, data = dataset)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Life_expectancy ~ GDP_per_capita + Schooling + Infant_deaths, \n    data = dataset)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.1502  -1.3384   0.3706   2.0890   9.3299 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     7.945e+01  1.440e+00  55.163  < 2e-16 ***\nGDP_per_capita  9.206e-05  1.811e-05   5.082 9.51e-07 ***\nSchooling      -2.783e-01  1.398e-01  -1.990   0.0481 *  \nInfant_deaths  -3.139e-01  1.560e-02 -20.117  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.285 on 175 degrees of freedom\nMultiple R-squared:  0.8746,\tAdjusted R-squared:  0.8725 \nF-statistic: 406.9 on 3 and 175 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\ntest_set$Predicted_Life_Expectancy <- predict(model, test_set)\n\nrmse <- sqrt(mean((test_set$Life_expectancy - test_set$Predicted_Life_Expectancy)^2))\nprint(paste(\"RMSE:\", rmse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"RMSE: 3.3581926443694\"\n```\n\n\n:::\n:::\n\n\n\nModel Strength:\n\nThe Adjusted R-squared of 0.8725 indicates that the model explains \\~87% of the variance in life expectancy.\n\nThe p-value (\\< 2.2e-16) confirms the model's statistical significance.\n\nKey Findings:\n\nGDP_per_capita: Positively correlated with life expectancy. A higher GDP indicates better access to healthcare and improved living standards.\n\nSchooling: Negatively correlated, though marginally significant (p = 0.0481). This counterintuitive result may reflect collinearity with other predictors.\n\nInfant_deaths: Strong negative correlation, highlighting its critical impact on life expectancy.\n\nThis low RMSE reflects accurate predictions of life expectancy across countries.\n\n\\###*Actual vs Predicted Life Expectancy*\n\nThe scatter plot below shows predicted vs actual life expectancy. The points cluster closely around the diagonal line, demonstrating the model's effectiveness.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(test_set, aes(x = Life_expectancy, y = Predicted_Life_Expectancy)) +\n  geom_point(color = \"blue\", alpha = 0.6) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", color = \"red\") +\n  theme_minimal() +\n  labs(\n    title = \"Actual vs Predicted Life Expectancy\",\n    x = \"Actual Life Expectancy (years)\",\n    y = \"Predicted Life Expectancy (years)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Life-Expectancy-Averaged_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\\###*Conclusion*\n\nThe analysis highlights that GDP_per_capita and Infant_deaths are the strongest predictors of life expectancy. Countries with higher GDP per capita typically enjoy better access to healthcare and improved living standards, which directly contribute to longer life spans. Conversely, high infant mortality rates have a significant negative impact on life expectancy, emphasizing the need for targeted interventions to improve maternal and child healthcare. The role of Schooling, however, requires further investigation. While it showed a marginally significant negative correlation in this model, this result could stem from multicollinearity or complex interactions with other predictors.\n\nLife expectancy varies widely across regions, with Africa exhibiting the lowest averages. This disparity underscores the critical need for policies that enhance healthcare access, reduce disease burden, and improve education in under-resourced areas. In contrast, developed regions such as North America, Europe, and Oceania report consistently higher life expectancy. These findings reflect the impact of robust healthcare systems, higher economic stability, and well-developed social infrastructure in sustaining healthier populations.\n",
    "supporting": [
      "Life-Expectancy-Averaged_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}